# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KNN <- function(data_x, data_y, K, mode = "cpp", precision = "float") {
    .Call(`_CWUKNN_KNN`, data_x, data_y, K, mode, precision)
}

